defmodule Day11Test do
  use ExUnit.Case
  doctest Day11

  test "problem1" do
    input = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """
    assert Day11.problem1(input, :io) == 374
  end

  test "problem2" do
    input = """
    ...#......
    .......#..
    #.........
    ..........
    ......#...
    .#........
    .........#
    ..........
    .......#..
    #...#.....
    """
    assert Day11.problem2(input, :io, 10) == 1030
    assert Day11.problem2(input, :io, 100) == 8410
  end
end
